CC=cc

CFLAGS = -I../../src -I../../../macx/glut/include -arch i386

SRCS = gizmo.c glutmui.c displaylist.c uicolor.c miscui.c mui.c vslider.c textlist.c button.c pulldown.c hslider.c
OBJS = $(SRCS:.c=.o)

all	: libmui.a

libmui.a: $(OBJS) $(GL_LIBS)
	rm -f libmui.a
	/usr/bin/libtool -static -o libmui.a $(OBJS)

clean:
	rm *.o 
	if [ -a libmui.a ]; then rm -f libmui.a; fi 


